INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (24375, 'Doja Cat', 'Hamilton Burg', 'doja.cat392@gmail.co', 'DojaCat2506');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (79629, 'Justin Bieber', 'Heather Landing', 'justin.bieber403@gmail.co', 'JustinBieber1811');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (86920, 'Ed Sheeran', 'Anthony Bridge', 'ed.sheeran36@gmail.net', 'EdSheeran2804');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (56565, 'Lady Gaga', 'Joshua Park', 'lady.gaga60@gmail.co', 'LadyGaga1603');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (10589, 'Katy Perry', 'Miles Burgs', 'katy.perry46@gmail.net', 'KatyPerry1208');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (97265, 'Ariana Grande', 'Olivia Dale', 'ariana.grande785@gmail.net', 'ArianaGrande1712');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (95319, 'Drake', 'Hayes Walks', 'drake.drake428@gmail.co', 'DrakeDrake1504');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (89367, 'Lady Gaga', 'Hutchinson Crossing', 'lady.gaga395@gmail.net', 'LadyGaga2611');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (50388, 'Doja Cat', 'Gould Land', 'doja.cat473@gmail.net', 'DojaCat2001');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (75979, 'Selena Gomez', 'Evan Trace', 'selena.gomez782@gmail.net', 'SelenaGomez1602');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (82613, 'Katy Perry', 'William Alley', 'katy.perry271@gmail.net', 'KatyPerry1501');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (44008, 'Rihanna', 'Durham Stream', 'rihanna.rihanna548@gmail.co', 'RihannaRihanna2001');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (99072, 'Olivia Rodrigo', 'Wolfe Well', 'olivia.rodrigo311@gmail.com', 'OliviaRodrigo0706');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (31193, 'Shawn Mendes', 'Powers Fort', 'shawn.mendes120@gmail.co', 'ShawnMendes0710');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (35078, 'Taylor Swift', 'Anthony Rest', 'taylor.swift342@gmail.net', 'TaylorSwift0407');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (42824, 'Beyoncé Knowles', 'Matthew Junctions', 'beyoncé.knowles532@gmail.net', 'BeyoncéKnowles0111');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (88934, 'Bruno Mars', 'Laura Highway', 'bruno.mars183@gmail.com', 'BrunoMars2107');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (94460, 'Miley Cyrus', 'Maria Rue', 'miley.cyrus174@gmail.net', 'MileyCyrus2307');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (39254, 'Ed Sheeran', 'Joshua Knolls', 'ed.sheeran166@gmail.com', 'EdSheeran1111');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (58863, 'Shawn Mendes', 'Jasmine Radial', 'shawn.mendes649@gmail.co', 'ShawnMendes0108');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (75754, 'Rihanna', 'Ruiz Lakes', 'rihanna.rihanna5@gmail.co', 'RihannaRihanna1010');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (52584, 'The Weeknd', 'Brent Cove', 'the.weeknd505@gmail.net', 'TheWeeknd1510');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (11826, 'Doja Cat', 'Robert Place', 'doja.cat360@gmail.net', 'DojaCat2611');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (54504, 'Beyoncé Knowles', 'Henderson Walks', 'beyoncé.knowles900@gmail.net', 'BeyoncéKnowles2801');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (25681, 'Harry Styles', 'Nicholson Wells', 'harry.styles466@gmail.com', 'HarryStyles0604');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (85414, 'Bruno Mars', 'April Pines', 'bruno.mars889@gmail.co', 'BrunoMars0109');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (77170, 'Shawn Mendes', 'Nicole Groves', 'shawn.mendes783@gmail.co', 'ShawnMendes2511');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (72572, 'Lady Gaga', 'Ballard Roads', 'lady.gaga221@gmail.com', 'LadyGaga0205');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (96178, 'Taylor Swift', 'Paul Valley', 'taylor.swift863@gmail.co', 'TaylorSwift2308');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (84132, 'Ariana Grande', 'Campos Fort', 'ariana.grande475@gmail.net', 'ArianaGrande1102');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (94646, 'Katy Perry', 'Jones Terrace', 'katy.perry61@gmail.net', 'KatyPerry0303');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (69930, 'Doja Cat', 'Ashley Trail', 'doja.cat906@gmail.com', 'DojaCat2405');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (48142, 'Katy Perry', 'Lee Club', 'katy.perry708@gmail.co', 'KatyPerry0311');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (78565, 'Drake', 'Thomas Underpass', 'drake.drake20@gmail.com', 'DrakeDrake2108');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (47010, 'Selena Gomez', 'Love Village', 'selena.gomez122@gmail.net', 'SelenaGomez2405');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (13040, 'Ariana Grande', 'Roberts Plain', 'ariana.grande642@gmail.net', 'ArianaGrande1809');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (15970, 'Billie Eilish', 'Robert Green', 'billie.eilish832@gmail.co', 'BillieEilish2211');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (36844, 'Ed Sheeran', 'Bender Divide', 'ed.sheeran109@gmail.com', 'EdSheeran2309');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (36061, 'Katy Perry', 'Hughes Mount', 'katy.perry695@gmail.com', 'KatyPerry1308');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (48881, 'Drake', 'Stephens Cliff', 'drake.drake851@gmail.com', 'DrakeDrake0604');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (46592, 'Dua Lipa', 'Jackson Vista', 'dua.lipa850@gmail.co', 'DuaLipa0902');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (47293, 'Selena Gomez', 'Smith Rue', 'selena.gomez366@gmail.net', 'SelenaGomez0406');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (78995, 'Shawn Mendes', 'Tonya Squares', 'shawn.mendes894@gmail.net', 'ShawnMendes1612');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (29137, 'Dua Lipa', 'Brown Valleys', 'dua.lipa350@gmail.co', 'DuaLipa0908');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (50432, 'Harry Styles', 'Fernandez Pike', 'harry.styles290@gmail.co', 'HarryStyles1702');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (62626, 'Billie Eilish', 'Benjamin Landing', 'billie.eilish274@gmail.co', 'BillieEilish1210');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (31866, 'Justin Bieber', 'Kelly Knoll', 'justin.bieber885@gmail.co', 'JustinBieber2712');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (50840, 'Ed Sheeran', 'Angela Stravenue', 'ed.sheeran340@gmail.com', 'EdSheeran2606');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (94968, 'Billie Eilish', 'Noah Isle', 'billie.eilish248@gmail.com', 'BillieEilish0204');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (13861, 'Miley Cyrus', 'Zavala Keys', 'miley.cyrus760@gmail.com', 'MileyCyrus1302');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (15345, 'Ariana Grande', 'Rose Ways', 'ariana.grande464@gmail.net', 'ArianaGrande1408');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (77182, 'Taylor Swift', 'Patterson Mall', 'taylor.swift876@gmail.com', 'TaylorSwift0303');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (90054, 'Selena Gomez', 'Jesse Row', 'selena.gomez811@gmail.com', 'SelenaGomez0505');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (96899, 'Ed Sheeran', 'Hartman Junctions', 'ed.sheeran341@gmail.net', 'EdSheeran2301');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (60760, 'Bruno Mars', 'Nelson Green', 'bruno.mars305@gmail.com', 'BrunoMars0410');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (72473, 'Dua Lipa', 'Hannah Corner', 'dua.lipa715@gmail.net', 'DuaLipa0909');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (36212, 'Beyoncé Knowles', 'Caldwell Extensions', 'beyoncé.knowles318@gmail.net', 'BeyoncéKnowles2103');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (94843, 'Ed Sheeran', 'Stone Dam', 'ed.sheeran549@gmail.co', 'EdSheeran2303');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (55642, 'Sam Smith', 'David Roads', 'sam.smith376@gmail.net', 'SamSmith2609');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (51359, 'Harry Styles', 'Kendra Bypass', 'harry.styles735@gmail.com', 'HarryStyles1704');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (57205, 'Bruno Mars', 'Baker Corner', 'bruno.mars208@gmail.co', 'BrunoMars1112');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (25796, 'Rihanna', 'Abbott Stream', 'rihanna.rihanna707@gmail.co', 'RihannaRihanna0411');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (24339, 'Olivia Rodrigo', 'Vang Turnpike', 'olivia.rodrigo218@gmail.com', 'OliviaRodrigo1903');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (10480, 'Olivia Rodrigo', 'French Curve', 'olivia.rodrigo102@gmail.co', 'OliviaRodrigo1903');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (79621, 'Harry Styles', 'Jenkins Drives', 'harry.styles292@gmail.com', 'HarryStyles2812');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (72598, 'Lady Gaga', 'Daniel Ferry', 'lady.gaga746@gmail.com', 'LadyGaga2009');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (14109, 'Dua Lipa', 'Tyler Mission', 'dua.lipa794@gmail.com', 'DuaLipa0206');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (33538, 'Beyoncé Knowles', 'Maria Shoal', 'beyoncé.knowles906@gmail.com', 'BeyoncéKnowles0204');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (59106, 'Lady Gaga', 'Williams Skyway', 'lady.gaga412@gmail.com', 'LadyGaga2309');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (31111, 'Shawn Mendes', 'Michael Vista', 'shawn.mendes857@gmail.co', 'ShawnMendes2610');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (38929, 'Lady Gaga', 'Karen Ridges', 'lady.gaga513@gmail.co', 'LadyGaga1807');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (86881, 'Ed Sheeran', 'Anderson Wells', 'ed.sheeran851@gmail.net', 'EdSheeran2003');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (82190, 'Sam Smith', 'Castillo Junction', 'sam.smith495@gmail.co', 'SamSmith1509');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (40033, 'Selena Gomez', 'Natasha Light', 'selena.gomez771@gmail.co', 'SelenaGomez2609');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (25352, 'Taylor Swift', 'Scott Rapid', 'taylor.swift157@gmail.net', 'TaylorSwift1612');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (69733, 'Olivia Rodrigo', 'Collins Loop', 'olivia.rodrigo4@gmail.net', 'OliviaRodrigo2006');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (57122, 'Shawn Mendes', 'Bryan Circles', 'shawn.mendes171@gmail.co', 'ShawnMendes2508');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (36648, 'Harry Styles', 'Flores Mall', 'harry.styles370@gmail.com', 'HarryStyles1111');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (67343, 'Shawn Mendes', 'Melissa Walks', 'shawn.mendes578@gmail.co', 'ShawnMendes0911');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (18715, 'Ariana Grande', 'Jamie Station', 'ariana.grande815@gmail.co', 'ArianaGrande2207');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (88759, 'Olivia Rodrigo', 'Lee Gardens', 'olivia.rodrigo658@gmail.co', 'OliviaRodrigo2412');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (19529, 'Harry Styles', 'Matthew Meadows', 'harry.styles741@gmail.net', 'HarryStyles0805');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (47682, 'Drake', 'Hebert Harbors', 'drake.drake598@gmail.co', 'DrakeDrake2405');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (29907, 'Rihanna', 'Jeffrey Burg', 'rihanna.rihanna327@gmail.co', 'RihannaRihanna1902');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (73513, 'Harry Styles', 'Michael Loop', 'harry.styles532@gmail.net', 'HarryStyles2104');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (45860, 'Sam Smith', 'Ruiz Underpass', 'sam.smith291@gmail.net', 'SamSmith1603');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (27562, 'Shawn Mendes', 'Mercado Villages', 'shawn.mendes61@gmail.co', 'ShawnMendes1005');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (95375, 'Bruno Mars', 'Anna Terrace', 'bruno.mars785@gmail.net', 'BrunoMars2708');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (53499, 'Sam Smith', 'Christina Summit', 'sam.smith300@gmail.net', 'SamSmith0706');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (67150, 'Drake', 'Brad Mill', 'drake.drake213@gmail.net', 'DrakeDrake1903');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (41470, 'Justin Bieber', 'Taylor Roads', 'justin.bieber590@gmail.net', 'JustinBieber2501');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (93782, 'Katy Perry', 'Matthew Mills', 'katy.perry837@gmail.com', 'KatyPerry0104');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (49110, 'Lady Gaga', 'Matthew Mountains', 'lady.gaga58@gmail.co', 'LadyGaga1311');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (75282, 'Lady Gaga', 'Sharon Garden', 'lady.gaga615@gmail.co', 'LadyGaga2309');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (13765, 'Justin Bieber', 'Jacqueline Vista', 'justin.bieber775@gmail.co', 'JustinBieber2007');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (42621, 'Shawn Mendes', 'Taylor Parks', 'shawn.mendes579@gmail.net', 'ShawnMendes1708');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (48723, 'Ed Sheeran', 'Katie Turnpike', 'ed.sheeran181@gmail.com', 'EdSheeran2406');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (41058, 'Justin Bieber', 'Jessica Meadows', 'justin.bieber184@gmail.net', 'JustinBieber0607');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (91646, 'Sam Smith', 'Kathleen Lights', 'sam.smith174@gmail.net', 'SamSmith0412');
INSERT INTO cliente (IDCliente, Nome, Endereco, Email, Senha)
VALUES (48517, 'Doja Cat', 'Denise Crest', 'doja.cat823@gmail.net', 'DojaCat2207');